name: auto-deploy with docker.yml

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: clone git repository
        uses: actions/checkout@v4

      - name: install jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

#      - name: copy application.properties

      - name: build jar
        run: chmod +x ./gradlew && ./gradlew clean build

      - name: build docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/web-app:latest .

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: docker image pull
        run: docker push ${{secrets.DOCKER_USER}}/web-app:latest

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name: deploy (ec2 접속, container 실행)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_KEY}}
          script_stop: true
          script: |
            docker stop myweb || true
            docker rm myweb || true
            docker pull ${{secrets.DOCKER_USER}}/web-app:latest
            docker run -d -p 8080:8080 --name myweb ${{secrets.DOCKER_USER}}/web-app:latest